spring:
  application:
    name: microservice-comsumer-movie
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8081