spring:
  application:
    name: microservice-discovery-eureka-ha
---
server:
  port: 8761
eureka:
  client:
    service-url:
#    将自己注册到peer2上去
     default-zone: http://peer2:8761/eureka
  instance:
#  指定当profile=peer1时，主机位peer1
    hostname: peer1
spring:
#指定profile=peer1
  profiles: peer1
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://peer1:8761/eureka
#